//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by bibedt.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_BIBITEMVIEW_FORM            101
#define IDD_DIALOGBAR_QUICKSEARCH       102
#define IDD_DIALOGBAR_FILTER_TEMPLATE   103
#define IDD_DIALOGBAR_FILTER            104
#define IDD_TOOLBAR_RECORD              105
#define IDD_OPTIONSPAGE_GENERAL         106
#define IDSEARCH                        107
#define IDS_STRING_LV_COL_KEY           108
#define IDS_STRING_REGKEY               109
#define IDS_STRING_LV_COL_AUTHOR        110
#define IDS_STRING_LV_COL_TITLE         111
#define IDS_STRING_FIELD                112
#define IDS_STRING_VALUE                113
#define IDS_STRING_NAME                 114
#define IDS_STRING_ADDREC               115
#define IDS_STRING_EDITREC              116
#define IDS_STRING_BIBFILTER            117
#define IDS_STRING_ALLFILTER            118
#define IDS_STRING_EDNTERKEY            119
#define IDS_STRING_INVALIDKEY           120
#define IDS_STRING_ENTERSTRING          121
#define IDS_STRING_CITEFORMAT           122
#define IDS_STRING_DUPLITEMS            123
#define IDS_STRING_TXTFILTER            124
#define IDS_STRING_COLCAPADD            125
#define IDS_STRING_COLPROMPT            126
#define IDS_STRING_HTMLFILTER           127
#define IDR_MAINFRAME                   128
#define IDR_BIBEDTTYPE                  129
#define IDS_STRING_OPTIONS_CAP          130
#define IDS_STRING_TBCAPTION_STD        131
#define IDS_STRING_RTFFILTER            132
#define IDD_DIALOG_OPTIONS              133
#define IDD_DIALOG_STRING               134
#define IDD_DIALOG_PREAMBLE             135
#define IDD_DIALOG_SEARCH               136
#define IDB_BITMAP_REQUIRED             137
#define IDS_STRING_NEWPREAMBLE          138
#define IDS_STRING_NODUPLICATES         139
#define IDS_STRING_NEWFIELD             140
#define IDS_STRING_FILTERCAPTION        141
#define IDD_DIALOG_RECSRC               142
#define IDS_STRING_CONDITION            143
#define IDS_STRING_NEWFILTER            144
#define IDS_STRING_NOFILTER             145
#define IDS_STRING_FILTEREXISTS         146
#define IDD_DIALOG_DUPLICATES           147
#define IDD_DIALOG_PROGRESS             148
#define IDD_DIALOG_COPYCITE             149
#define IDS_STRING_QSCAPTION            150
#define IDD_DIALOG_COLUMNS              151
#define IDD_DIALOG_INPUTBOX             152
#define IDS_STRING_ALLFIELDS            153
#define IDS_STRING_ABSTRACT             154
#define IDS_STRING_AUXFILTER            155
#define IDS_STRING_KEYNOTFOUND          156
#define IDD_OPTIONSPAGE_FILES           157
#define IDB_BITMAP_ITEMS                158
#define IDD_OPTIONSPAGE_PRINT           159
#define IDS_STRING_ERROR                160
#define IDS_STRING_PARSING              161
#define IDD_DIALOG_SOURCE               162
#define IDD_DIALOG_FINDTEXT             163
#define IDD_DIALOG_REPLACETEXT          164
#define IDS_STRING_AUXSUCC              165
#define IDS_STRING_FOUNDKEY             166
#define IDR_MENU_SOURCEVIEW             167
#define IDB_BITMAP_HEADER_SORT          168
#define IDB_BITMAP_LISTVIEW             169
#define IDR_MENU_LISTVIEW               170
#define IDS_STRING_AUXSTAT              171
#define IDS_STRING_CROSSREFCAP          172
#define IDD_DIALOG_FILTER               173
#define IDS_STRING_BIBDATA              174
#define IDS_STRING_BIBSTYLE             175
#define IDS_STRING_WARNING              176
#define IDD_DIALOGBAR_QUICKSEARCH_TEMPLATE 177
#define IDR_MENU_FIELDLIST              178
#define IDR_TOOLBAR_RECORD              179
#define IDS_STRING_NOBIBDATA            180
#define IDC_CURSOR_LINKHAND             181
#define IDD_DIALOG_GENFROMAUX           182
#define IDD_DIALOG_KEYS                 183
#define IDC_SCINCTRL                    184
#define IDD_DIALOG_ONLINESEARCH         185
#define IDD_DIALOG_FINDDUPLOP           186
#define IDD_DIALOG_EDITSEARCHPROFILES   187
#define IDI_ICON_ONLINESEARCH           188
#define IDC_BUTTON_ENC_BROWSE           189
#define IDC_EDIT_ENCHTML                190
#define IDC_EDIT_FIELD_VALUE            191
#define IDC_BUTTON_ENCHTML_BROWSE       192
#define IDC_BUTTON_ADDFIELD             193
#define IDC_EDIT_ENCRTF                 194
#define IDC_BUTTON_FIELDEDIT            195
#define IDC_BUTTON_ENCRTF_BROWSE        196
#define IDC_BUTTON_FIELDREMOVE          197
#define IDC_CHECK_SORTCASE              198
#define IDC_BUTTON_APPLY                199
#define IDC_COMBO_REPLACETEXT           200
#define IDC_SPIN_RECSTART               201
#define IDC_STATIC_RECEND               202
#define IDC_STATIC_VERSION              203
#define IDC_EDIT_RECEND                 204
#define IDC_SPIN_RECEND                 205
#define IDC_EDIT_KEY                    206
#define IDC_STATIC_WEB                  207
#define IDC_CHECK_BACKUP                208
#define IDC_CHECK_ROWSELECT             209
#define IDC_CHECK_GRIDLINES             210
#define IDC_EDIT_TEMPLATEFILE           211
#define IDC_BUTTON_TEMPLATE_BROWSE      212
#define IDC_CHECK_TRANSLATE             213
#define IDC_EDIT_ENC                    214
#define IDC_LIST_FIELDS                 215
#define IDC_EDIT_SEARCHPROFILES         216
#define IDC_BUTTON_SPROF_BROWSE         217
#define IDC_COMBO_TYPE                  218
#define IDC_EDIT_PEAMBLE                219
#define IDC_LIST_STRINGS                220
#define IDC_EDIT_VALUE                  221
#define IDC_BUTTON_ADD                  222
#define IDC_BUTTON_EDIT                 223
#define IDC_BUTTON_REMOVE               224
#define IDC_CHECK_MATCHCASE             225
#define IDC_CHECK_WHOLEWORDS            226
#define IDC_CHECK_SELONLY               227
#define IDC_EDIT_SEARCHTEXT             228
#define IDC_BUTTON_APPLAY               229
#define IDC_EDIT_LINELENGTH             230
#define IDC_EDIT_CITEFORMAT             231
#define IDC_EDIT_SRC                    232
#define IDC_BUTTON_SOURCE               233
#define IDC_BUTTON_UNDO                 234
#define IDC_EDIT_TERM                   235
#define IDC_LIST_RESULT                 236
#define IDC_COMBO_KIND                  237
#define IDC_COMBO_WHERE                 238
#define IDC_COMBO_FIELDS                239
#define IDC_TREE_ITEMS                  240
#define IDC_EDIT_SOURCE                 241
#define IDC_BUTTON_SELECT               242
#define IDC_PROGRESS_MAIN               243
#define IDC_BUTTON_GEYGENERATE          244
#define IDC_RADIO_CITE                  245
#define IDC_RADIO_NOCITE                246
#define IDC_RADIO_CUSTOM                247
#define IDC_RADIO_KEYONLY               248
#define IDC_LIST_KEYS                   249
#define IDC_CHECK_SHOWCITEDLG           250
#define IDC_COMBO_CUSTOM                251
#define IDC_CHECK_SORTONSAVE            252
#define IDC_LIST_COLUMNS                253
#define IDC_BUTTON_UP                   254
#define IDC_BUTTON_DOWN                 255
#define IDC_EDIT_TEXT                   256
#define IDC_STATIC_PROMPT               257
#define IDC_EDIT_ENCTEX                 258
#define IDC_BUTTON_ENCTEX_BROWSE        259
#define IDC_STATIC_CUSTOM               260
#define IDC_EDIT_TOP                    261
#define IDC_EDIT_BOTTOM                 262
#define IDC_EDIT_LEFT                   263
#define IDC_EDIT_RIGHT                  264
#define IDC_COMBO_UNITS                 265
#define IDC_LIST_PREAMBLES              266
#define IDC_SPIN_TOP                    267
#define IDC_SPIN_TOP2                   268
#define IDC_SPIN_TOP3                   269
#define IDC_SPIN_TOP4                   270
#define IDC_STATIC_SOURCE               271
#define IDC_COMBO_TEXT                  272
#define IDC_CHECK_OPENLAST              273
#define IDC_BUTTON_REPLACE              274
#define IDC_BUTTON_REPLACEALL           275
#define IDC_CHECK_REGEXPR               276
#define IDC_RADIO_UP                    277
#define IDC_RADIO_DOWN                  278
#define IDC_BUTTON_MARK                 279
#define IDC_STATIC_SL_VERSION           280
#define IDC_STATIC_LB_VERSION           281
#define IDC_STATIC_EMAIL                282
#define IDC_BUTTON_BOOKMARK             283
#define IDC_COMBO_FILTER                284
#define IDC_LIST_FILTERS                285
#define IDC_EDIT_COND                   286
#define IDC_EDIT_FIELD                  287
#define IDC_STATIC_COND                 288
#define IDC_STATIC_FIELD                289
#define IDC_BUTTON_QUICKSEARCH          290
#define IDC_EDIT_QUICKSEARCH            291
#define IDC_EDIT_QSFIELDS               292
#define IDC_CHECK_REPLSPECCHAR          293
#define IDC_CHECK_SCOLLSEL              294
#define IDC_COMBO_QS_FIELD              295
#define IDC_EDIT_AUXFILE                296
#define IDC_EDIT_TARGETFILE             297
#define IDC_BUTTON_AUXBROWSE            298
#define IDC_BUTTON_TARGETBROWSE         299
#define IDC_EDIT_LOG                    300
#define IDC_EDIT_PREVIEW                301
#define IDC_CHECK_REGEX                 302
#define IDC_CHECK_AUTOCOMPL             303
#define IDC_EDIT_HOST                   304
#define IDC_EDIT_PORT                   305
#define IDC_EDIT_DATABASE               306
#define IDC_EDIT_SEARCHFOR              307
#define IDC_LIST_RESULTS                308
#define IDC_EDIT_RECSTART               309
#define IDC_STATIC_SEARCH               310
#define IDC_STATIC_SERVER               311
#define IDC_EDIT_USER                   312
#define IDC_EDIT_GROUP                  313
#define IDC_EDIT_PASS                   314
#define IDC_EDIT_PROXY                  315
#define IDC_STATIC_USER                 316
#define IDC_BUTTON_IMPORT               317
#define IDC_STATIC_PORT                 318
#define IDC_STATIC_HOST                 319
#define IDC_STATIC_PROXY                320
#define IDC_STATIC_USERNAME             321
#define IDC_STATIC_GROUP                322
#define IDC_STATIC_PASS                 323
#define IDC_STATIC_DATABASE             324
#define IDC_STATIC_QUERY                325
#define IDC_SPIN_PORT                   326
#define IDC_RADIO_QT_PREFIX             327
#define IDC_RADIO_QT_CQL                328
#define IDC_STATIC_QT                   329
#define IDC_STATIC_RECSTART             330
#define IDC_BUTTON_NEWPROFILE           331
#define IDC_COMBO_PROFILES              332
#define IDC_SPIN_LINELENGTH             333
#define IDC_BUTTON_EDITPROFILE          334
#define IDC_CHECK_EXACT                 335
#define IDC_CHECK_CASESENS              336
#define IDC_LIST_PROFILES               337
#define IDC_BUTTON_RENAME               338
#define IDC_STATIC_RESULTS              339
#define IDC_EDIT_RAW                    340
#define IDC_BUTTON_NEXT                 341
#define IDC_RADIO_QT_CCL                342
#define IDC_CHECK_SAVEPASS              343
#define IDC_BUTTON_HELP                 344
#define IDS_STRING_NOSTYLE              345
#define IDS_STRING_MANUALNOTFOUND       346
#define IDS_STRING_FILECHANGED          347
#define IDS_STRING_FILEDELETED          348
#define IDS_STRING_STRANGEQUERYTYPE     349
#define IDS_STRING_YAZEXCEPTION         350
#define IDS_STRING_XMLFILTER            351
#define IDS_STRING_NEWPROFCAP           352
#define IDS_STRING_NEWPROFPROMPT        353
#define IDS_STRING_SEARCHRESULT         354
#define IDS_STRING_SEARCHRESULTSNUM     355
#define IDS_STRING_RENPROF              356
#define IDS_STRING_RENPROFPROMPT        357
#define IDC_LIST_MISSINGFIELDS          358
#define IDS_STRING_NOMISSING            359
#define IDS_STRING_LOADERR              360
#define IDC_EDIT_DOIURL                 361
#define IDC_LIST_FILTER                 362
#define IDD_DIALOG_APPLYFILTER          363
#define IDC_STATIC_NILSEMAIL            364
#define IDC_STATIC_STIEVIE              365
#define IDC_STATIC_NILS                 366
#define IDC_EDIT_ENCXML                 367
#define IDC_BUTTON_ENCXML_BROWSE        368
#define IDC_EDIT_XSL                    369
#define IDC_BUTTON_XSL_BROWSE           370
#define IDS_STRING_XSLFILTER            371
#define IDC_LIST_EXPORTER               372
#define IDC_EDIT_STYLEFILE              373
#define IDC_BUTTON_BROWSE_STYLE         374
#define IDC_COMBO_ENCODING              375
#define IDC_BUTTON_EXPORTER_ADD         376
#define IDC_BUTTON_EXPORTER_RENAME      377
#define IDC_BUTTON_EXPORTER_REMOVE      378
#define IDS_STRING_XMLPARSEERR          379
#define IDD_OPTIONSPAGE_EXPORTER        380
#define IDD_EXPORT_FILTER               381
#define IDC_EDIT_EXTENSION              382
#define IDC_EDIT_FILTER                 383
#define IDS_STRING_ADDEXPORTER          384
#define IDS_STRING_ADDEXPORTER_PROMPT   385
#define IDD_OPTIONSPAGE_DEFEDITOR       386
#define IDC_EDIT1                       387
#define IDC_EDIT_TLCLASS                388
#define IDC_EDIT_CHCLASS                389
#define IDC_EDIT2                       390
#define IDS_STRING_XSLPARSEERR          391
#define IDR_MENU_PREVIEW                392
#define IDS_GENERATEKEYS_PROMPT         393
#define IDB_DONATE                      394
#define IDC_DONATE                      395
#define IDS_DONATE_URL                  396
#define IDS_STRING_RENAMEEXPORTER       397
#define IDC_EDIT_CONFIGDIR              398
#define IDC_BUTTON_CONFIGDIR_BROWSE     399
#define IDS_STRING_SEL_CFGDIR           400
#define IDC_BUTTON_SEARCH_MARKALL       401
#define IDD_OPTIONSPAGE_LANGUAGE        402
#define IDC_COMBO_LANGS                 403
#define IDC_CHECK_REQFIELDS             404
#define IDS_STRING_EXT_BIB              405
#define IDS_STRING_EXT_AUX              406
#define IDS_STRING_UNKNOWN_XSLERROR     407
#define IDS_ERR_NOTEMPLATEFILE          408
#define IDC_CHECK_NOSAVE                409
#define IDS_ERR_NOSUCHLANGUAGE          410
#define IDS_ERR_LOADINGLANGLIB          411
#define IDD_OPTIONSPAGE_PREVIEW         412
#define IDC_COMBO_FIELD                 413
#define IDC_COMBO2                      414
#define IDC_COMBO3                      415
#define IDC_COMBO_FNT_MONO              416
#define IDC_COMBO_FNT_SANS              417
#define IDC_COMBO_FNT_PROP              418
#define IDD_DIALOG_VALUELIST            419
#define IDC_COMBO1                      420
#define IDC_REFRESH                     421
#define IDC_LIST_VALUES                 422
#define IDS_COLUMNVALUE_TEXT            423
#define IDR_MENU_VALUELIST              424
#define ID_BUTTON_FINDNEXT              32771
#define ID_RECORD_ADD                   32772
#define ID_RECORD_REMOVE                32773
#define ID_BUTTON_GENERATE              32774
#define ID_SEARCH                       32775
#define ID_CLOSE                        32776
#define ID_RECORD_SORTED                32777
#define ID_VIEW_ROWSELECT               32778
#define ID_VIEW_GRIDLINES               32779
#define ID_VIEW_OPTIONS                 32780
#define ID_INDICATOR_RECCOUNT           32781
#define ID_FILE_EXPORT_SUBSET           32782
#define ID_FILE_EXPORT_HTML             32783
#define ID_FILE_EXPORT_TEXT             32784
#define ID_FILE_IMPORT                  32785
#define ID_RECORD_UP                    32786
#define ID_RECORD_DOWN                  32787
#define ID_RECORD_EDIT                  32788
#define ID_EDIT_DELETE                  32789
#define ID_EDIT_PREAMBLE                32790
#define ID_EDIT_STRINGS                 32791
#define ID_EDIT_SEARCH                  32792
#define ID_EDIT_FINDNEXT                32793
#define ID_EDIT_COPYCITATION            32794
#define ID_RECORD_SOURCE                32795
#define ID_INDICATOR_TYPE               32796
#define ID_EDIT_SELECTALL               32797
#define ID_INDICATOR_SELCOUNT           32798
#define ID_RECORD_FINDDUPLICATE         32799
#define ID_VIEW_COLUMNS                 32800
#define ID_FILE_EXPORT_RTF              32803
#define ID_HELP_README                  32804
#define ID_HELP_CHANGELOG               32805
#define ID_FILE_SOURCE                  32807
#define ID_RECORD_PREVIOUS              32815
#define ID_SEARCH_CLEARBOOKMARKS        32823
#define ID_SEARCH_TOGGLEBOOKMARK        32824
#define ID_SEARCH_NEXTBOOKMARK          32825
#define ID_SEARCH_PREVIOUSBOOKMARK      32826
#define ID_SEARCH_FIND                  32827
#define ID_SEARCH_FINDNEXT              32828
#define ID_SEARCH_REPLACE               32829
#define ID_SEARCH_GOTORECORD            32830
#define ID_SOURCEVIEW_UNDO              32831
#define ID_SOURCEVIEW_REDO              32832
#define ID_SOURCEVIEW_CUT               32833
#define ID_SOURCEVIEW_COPY              32834
#define ID_SOURCEVIEW_PASTE             32835
#define ID_SOURCEVIEW_SELECTALL         32836
#define ID_SOURCEVIEW_DELETE            32837
#define ID_SOURCEVIEW_EDITITEM          32838
#define ID_POPUP_FIND                   32839
#define ID_POPUP_TOGGLEBOOKMARK         32840
#define ID_SEARCH_FINDDUPLICATE         32841
#define ID_EDIT_COPYKEY                 32842
#define ID_POPUP_COPYKEY                32844
#define ID_VIEW_TOOLBARS_FILTER         32852
#define ID_VIEW_FILTER                  32853
#define ID_VIEW_TOOLBARS_RECORD         32860
#define ID_VIEW_TOOLBARS_QUICKSEARCH    32861
#define ID_FIELDLIST_POPUP_ADD          32862
#define ID_FIELDLIST_POPUP_EDIT         32863
#define ID_FIELDLIST_POPUP_REMOVE       32864
#define ID_BUTTON32866                  32866
#define ID_BUTTON32867                  32867
#define ID_BUTTON32868                  32868
#define ID_BUTTON32869                  32869
#define ID_BUTTON32870                  32870
#define ID_BUTTON32871                  32871
#define ID_VIEW_FOLDALL                 32872
#define ID_VIEW_EXPANDALL               32873
#define ID_RECORD_COPYKEY               32874
#define ID_HELP_MANUAL                  32875
#define ID_POPUP_BROWSE                 32877
#define ID_VIEW_PREVIEW                 32878
#define ID_TOOLS_GENERATEFROMAUX        32880
#define ID_POPUP_CROSSREF               32881
#define ID_TOOLS_OPTIONS                32882
#define ID_HELP_CHECKFORUPDATE          32883
#define ID_TOOLS_FILTER                 32884
#define ID_SEARCH_REGULAREXPRESSION     32885
#define ID_RECORD_GENERATEKEY           32886
#define ID_TOOLS_ONLINESEARCH           32888
#define ID_EDIT_MODIFIED                32890
#define ID_POPUP_FILTER                 32891
#define ID_FILE_EXPORT_XML              32892
#define ID_VIEW_PREIVEW                 32893
#define ID_VIEW_TOOLBARS_CUSTOMIZE      32894
#define ID_VIEW_LISTVIEW                32897
#define ID_VIEW_SOURCEVIEW              32898
#define ID_VIEW_RECORD                  32899
#define ID_VIEW_TOGGLEQUICKSEARCH       32902
#define ID_FILE_EXPORT                  32903
#define ID_RECORD_INSERTKEY             32904
#define ID_PREVIEW_COPYLINK             32908
#define ID_PREVIEW_VIEWSOURCE           32909
#define ID_TOOLS_GENERATEKEYS           32910
#define ID_POPUP_FOLDALL                32911
#define ID_POPUP_EXPANDALL              32912
#define ID_POPUP_LOCALURL               32913
#define ID_PREVIEW_COPYHTML             32914
#define ID_TOOLS_VALUELIST              32915
#define ID_POPUP_SELECT                 32916

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                1
#define _APS_NEXT_RESOURCE_VALUE        23
#define _APS_NEXT_COMMAND_VALUE         32917
#define _APS_NEXT_CONTROL_VALUE         1244
#define _APS_NEXT_SYMED_VALUE           61608
#endif
#endif
